services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 7007:7007
      - 9229:9229
    command: npm run dev
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres:14
    env_file:
      - .env.development
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  # migration:
  #   container_name: migration
  #   build:
  #     context: .
  #   env_file:
  #     - .env.development
  #   command: sh -c "
  #     echo 'Waiting for postgres...' &&
  #     sleep 3 &&
  #     npx sequelize-cli db:migrate"
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - postgres

volumes:
  pgdata: